name: Flake8

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  linting-flake8:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"
      - name: Lint with Flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          flake8 --count --statistics --show-source --jobs=$(nproc) .
