name: pipenv

on:
  push:
    branches:
    - main
  pull_request:

jobs:

  pipenv-dev:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install the package
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev
      - name: Test with pytest
        run: |
          pipenv run flake8 --count --statistics --show-source --jobs=$(nproc) .
          pipenv run black --check --diff .
          pipenv run pytest tests --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
